version: '3.8'

services:
  photo-gallery:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./data/database:/app/data/database
      - ./data/thumbnails:/app/data/thumbnails
      - ./data/config:/app/data/config
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  database:
    driver: local
  thumbnails:
    driver: local
  config:
    driver: local
